[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Download'
    pageRef = '/download'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
