baseURL = 'https://maybedont.ai/'
languageCode = 'en-us'
title = "Maybe Don't, AI"
theme = 'basic'

# Navigation menus
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 20
  [[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 30
  [[menu.main]]
    name = "Pricing"
    url = "/pricing/"
    weight = 40
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 50
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 10
  [[menu.footer]]
    name = "Terms of Service"
    url = "/terms/"
    weight = 20
  [[menu.footer]]
    name = "Cookie Policy"
    url = "/cookies/"
    weight = 30

# Social media links
[params]
  [params.social]
    linkedin = "https://www.linkedin.com/company/maybe-dont-ai"

disableKinds = ["taxonomy", "term"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
