baseURL = 'https://maybedont.ai/'
languageCode = 'en-us'
title = "Maybe Don't AI"
theme = 'basic'


disableKinds = ["taxonomy", "term"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
